### ISSUE TITLE
Update links in readme

### ISSUE THREAD

**Issue by 2br-2b** [t7ko/jdotxt#23]
Lots of the links point towards the old repo. We need to point them towards the new repo.

**Comment by t7ko** [comment]
I thought about it some time -- but decided to not do it.  If I do it -- there won't be an easy way to merge back changes from my repo into original repo.  And I wanted to leave the way for author to easily re-integrate back my changes.

I may re-think this decision in future, but not right now.

**Comment by 2br-2b** [comment]
Fair enough. Thanks for continuing to work on the project, though!
