### ISSUE TITLE
Calendar icon makes tasks overly tall

### ISSUE THREAD

**Issue by sebawild** [t7ko/jdotxt#33]
I love the new calendar icon functionality you added, @t7ko!
But for my taste, it takes up to much vertical space. I have many tasks with short text, and with this update, I see 6 instead of 10 task in the same-size window.
Any change we could place the icon buttons differently? Maybe as a horizontal list instead, in the line of the date?

**Comment by t7ko** [comment]
Yes I noticed this issue as well -- but only recently, as I don't use this view myself...  I have it in my todo to fix it.

**Comment by t7ko** [comment]
@sebawild -- pls try this release and let me know if it works for you.

https://github.com/t7ko/jdotxt/releases/tag/v1.6-alpha2

**Comment by sebawild** [comment]
That's brilliant, works really well! Thanks for the quick fix
