### ISSUE TITLE
[enhancement] Enable dark mode

### ISSUE THREAD

**Issue by sphenotux** [t7ko/jdotxt#34]
Got this idea from a user via the matrix/element group for SimpleTask and thought it would be a nice idea to bring in. Do not know how much work it means to adjust the IMHO as of now hard coded (?) colour settings as variables.
Let the user switch between e.g. _default_ and _dark mode_, via toggle button..?

**Comment by t7ko** [comment]
I don't think I'll be able to take this myself, and I don't see a lot of contributors now.  I actually see only two.  So I guess your idea won't be implemented any time soon unless you take a stab at it yourself.  Sorry.

**Comment by sphenotux** [comment]
I appreciate your honest reply, @t7ko . Indeed I was asking for "a friend" - someone who used the matrix/Element channel for SimpleTask - todo.txt.
Will close this for now. To whom it may concern: Feel free to re-open this topic.
BR
